spring:
  application:
    name: spring_application_name_jzh_shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/jzh_shop?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 10.169.5.191
      port: 6379
      database: 6

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #调试输出的sql
    #map-underscore-to-camel-case: false #如果java还是下划线。mybatis这里默认是true，会把mysql下划线转为java的驼峰命名法

rocketmq:
  name-server: 10.169.5.191:9876
  producer:
    #group: index12306_aggregation-service_common-message-execute_pg
    group: jzh-message-execute_pg
    #send-message-timeout: 2000
    send-message-timeout: 10000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
