spring:
  application:
    name: spring_application_name_jzh_shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    MyBatis的update语句的返回值改为从匹配数改为受影响的记录数，向mysql连接添加useAffectedRows=true一个参数即可。
    #但我这里update似乎不用配，因为我限制了a-b>0
    url: jdbc:mysql://127.0.0.1:3306/jzh_shop?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 6
      password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #调试输出的sql
    #map-underscore-to-camel-case: false #如果java还是下划线。mybatis这里默认是true，会把mysql下划线转为java的驼峰命名法


#legion需要修改什么ip
#spring：
  #rocketMQ修改为hass的
  #canal：修改为legion的客观ip
  #F:\canal.deployer-1.1.6\conf\canal.properties  修改为rocketeMQ的hass地址

rocketmq:
  name-server: 192.168.31.137:9876
  producer:
    group: index12306_aggregation-service_common-message-execute_pg
    #group: jzh-message-execute_pg
    #send-message-timeout: 2000
    send-message-timeout: 10000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1


canal:
  #server: 192.168.31.137:11111  #haee的canal的地址
  server: 192.168.31.136:11111  #log'i'o'n的cannal地址
  destination: jzh_index12306_canal_ticket-service_common-sync_topic

#自定义
ticket:
  availability:
    cache-update:
      type: binlog
